# Generated by Django 4.0.3 on 2022-07-01 11:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fac_id', models.CharField(max_length=10)),
                ('docs', models.FileField(blank=True, null=True, upload_to='docs')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='day_tipe',
            field=models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Очно-вечерняя', 'Очно-вечерняя')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='exam_one',
            field=models.CharField(blank=True, choices=[('MATH', 'Математика'), ('RUSS', 'Русский Язык'), ('CHEM', 'Химия'), ('PHYS', 'Физика'), ('SOCL', 'Обществознание'), ('INFO', 'Информатика'), ('FRLN', 'Иностранный язык')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='exam_three',
            field=models.CharField(blank=True, choices=[('MATH', 'Математика'), ('RUSS', 'Русский Язык'), ('CHEM', 'Химия'), ('PHYS', 'Физика'), ('SOCL', 'Обществознание'), ('INFO', 'Информатика'), ('FRLN', 'Иностранный язык')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='exam_two',
            field=models.CharField(blank=True, choices=[('MATH', 'Математика'), ('RUSS', 'Русский Язык'), ('CHEM', 'Химия'), ('PHYS', 'Физика'), ('SOCL', 'Обществознание'), ('INFO', 'Информатика'), ('FRLN', 'Иностранный язык')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='time_edu',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='type_edu',
            field=models.CharField(blank=True, choices=[('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Асперантура', 'Асперантура')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('N', 'Не хочу говорить')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='speciality',
            name='faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='mainsite.faculty'),
        ),
    ]
